version: '3.2'
services:
  cli: 
    build:
      context: .
      args:
        github_token: ___
        jenkins_user: ___
        jenkins_password: ___
    depends_on:
      - redis

  redis:
    image: redis:alpine